# Generated by Django 4.0.7 on 2022-09-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
