# Generated by Django 4.1.1 on 2022-09-15 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='date_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
