# Generated by Django 4.1.1 on 2022-09-15 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mailing_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='date_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
