# Generated by Django 4.0.7 on 2022-09-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_client_mobile_operator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_operator_code',
            field=models.IntegerField(),
        ),
    ]
